blank_issues_enabled: false
contact_links:
  - name: WebUI Community Support
    url: https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions
    about: Please ask and answer questions here.
